# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='code',
            field=models.CharField(default='SAM', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
